spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shoes
    username: root
    password: qwer1234!
  profiles:
    active: jdbc
  mvc:
    hiddenmethod:
      filter:
        enabled: true